name: Codecov Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: spider test cover 
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Install requirements
      run: pip install -r Protótipos/Extrator_V2/requirements.txt
    - name: Run tests and collect coverage
      run: Protótipos/Extrator_V2/tests --cov=extrator_v2 --cov-report=xml
    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v3
